/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyquiz.client;

import easyquiz.Ans3Question;
import easyquiz.Question;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author aland
 */
public class Ans3QuestionPane extends javax.swing.JPanel {
    private CountdownThread countdownThread;
    private Question question;
    private int selected;
    private ArrayList<JButton> buttons;
    private int obtainedPoints;
    private long deadline;
    
    /**
     * Creates new form Ans3Question
     */
    public Ans3QuestionPane() {
        initComponents();
        this.selected = -1;
        this.buttons = new ArrayList<>();
        this.buttons.add(opt1Button);
        this.buttons.add(opt2Button);
        this.buttons.add(opt3Button);
    }

    public int getSelected() {
        return selected;
    }

    public int getObtainedPoints() {
        return obtainedPoints;
    }

    public boolean correct() {
        return this.selected == this.question.getCorrectOptionIndex();
    }
    
    public void showResults() {
        if (this.correct()) {
            System.out.println(this.obtainedPoints);
            JButton button = this.buttons.get(this.selected);
            button.setBackground(new Color(52, 235, 107));
            MainFrame.getInstance().addScore(this.obtainedPoints);
            MainFrame.getInstance().sendAnswer(this.selected, this.obtainedPoints);
        } else {
            JButton wrong = this.buttons.get(this.selected);
            JButton correct = this.buttons.get(this.question.getCorrectOptionIndex());
            wrong.setBackground(new Color(235, 52, 52));
            correct.setBackground(new Color(52, 235, 107));
        }
    }
    
    public void selectOption(int index) {
        if (this.selected > -1)
            return;
        
        this.selected = index;
        
        long remaining = this.deadline - System.currentTimeMillis();
        this.obtainedPoints = correct() ? (int) (remaining / 15) : 0;

        JButton button = this.buttons.get(index);
        button.setBackground(new Color(52, 171, 235));
        
        for (JButton b : this.buttons) {
            b.setFocusable(false);
        }
    }
    
    public void showQuestion(Ans3Question quest, long deadline) {
        for (JButton b : this.buttons) {
            b.setFocusable(true);
            b.setBackground(new Color(244, 243, 246));
        }
        
        this.deadline = deadline;
        this.question = quest;
        this.selected = -1;
        this.obtainedPoints = 0;
        ArrayList<String> options = quest.getOptions();
        
        questionLabel.setText(quest.getQuestion());
        opt1Button.setText(options.get(0));
        opt2Button.setText(options.get(1));
        opt3Button.setText(options.get(2));
        
        this.countdownThread = new CountdownThread(deadline, this.countdownLabel, () -> {
            if (this.selected > -1) {
                this.showResults();
            }
            
            //MainFrame.getInstance().showQuestion(question, deadline);
        });
        
        this.countdownThread.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        opt1Button = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 25), new java.awt.Dimension(20, 25), new java.awt.Dimension(20, 25));
        opt2Button = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 25), new java.awt.Dimension(20, 25), new java.awt.Dimension(20, 25));
        opt3Button = new javax.swing.JButton();
        countdownLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 232, 227));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        questionLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(25, 29, 99));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Your question goes here");
        questionLabel.setAlignmentX(0.5F);
        questionLabel.setMaximumSize(new java.awt.Dimension(500, 150));
        add(questionLabel);

        opt1Button.setBackground(new java.awt.Color(244, 243, 246));
        opt1Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt1Button.setText("Continue");
        opt1Button.setAlignmentX(0.5F);
        opt1Button.setFocusPainted(false);
        opt1Button.setMaximumSize(new java.awt.Dimension(150, 32));
        opt1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ButtonActionPerformed(evt);
            }
        });
        add(opt1Button);
        add(filler1);

        opt2Button.setBackground(new java.awt.Color(244, 243, 246));
        opt2Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt2Button.setText("Continue");
        opt2Button.setAlignmentX(0.5F);
        opt2Button.setFocusPainted(false);
        opt2Button.setMaximumSize(new java.awt.Dimension(150, 32));
        opt2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ButtonActionPerformed(evt);
            }
        });
        add(opt2Button);
        add(filler2);

        opt3Button.setBackground(new java.awt.Color(244, 243, 246));
        opt3Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt3Button.setText("Continue");
        opt3Button.setAlignmentX(0.5F);
        opt3Button.setFocusPainted(false);
        opt3Button.setMaximumSize(new java.awt.Dimension(150, 32));
        opt3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ButtonActionPerformed(evt);
            }
        });
        add(opt3Button);

        countdownLabel.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        countdownLabel.setForeground(new java.awt.Color(0, 153, 0));
        countdownLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countdownLabel.setText("5");
        countdownLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        countdownLabel.setAlignmentX(0.5F);
        countdownLabel.setMaximumSize(new java.awt.Dimension(150, 86));
        add(countdownLabel);
    }// </editor-fold>//GEN-END:initComponents

    private void opt1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ButtonActionPerformed
        this.selectOption(0);
    }//GEN-LAST:event_opt1ButtonActionPerformed

    private void opt2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ButtonActionPerformed
        this.selectOption(1);
    }//GEN-LAST:event_opt2ButtonActionPerformed

    private void opt3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ButtonActionPerformed
        this.selectOption(2);
    }//GEN-LAST:event_opt3ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countdownLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton opt1Button;
    private javax.swing.JButton opt2Button;
    private javax.swing.JButton opt3Button;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
